// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSimple(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ExportSimple'](arg1, arg2, arg3);
}

export function FFmpegVersion() {
  return window['go']['backend']['App']['FFmpegVersion']();
}

export function Now() {
  return window['go']['backend']['App']['Now']();
}

export function Platform() {
  return window['go']['backend']['App']['Platform']();
}

export function Transcribe(arg1) {
  return window['go']['backend']['App']['Transcribe'](arg1);
}
