// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSimple(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FFmpegVersion():Promise<string>;

export function Now():Promise<number>;

export function Platform():Promise<string>;

export function Transcribe(arg1:string):Promise<string>;
